package it.nextworks.nfvmano.catalogue.blueprint.elements;

public enum EveSite {
	
	ITALY_TURIN,
	SPAIN_5TONIC,
	FRANCE_PARIS,
	FRANCE_CHATILLON, 
	FRANCE_SACLAY,
	FRANCE_SOPHIA_ANTIPOLIS,
	FRANCE_NICE,
	FRANCE_RENNES,
	FRANCE_LANNION,
	GREECE_ATHENS,
	ITALY_5GROWTH_COMAU,
	SPAIN_5GROWTH_INNOVALIA


}
