package it.nextworks.nfvmano.catalogue.blueprint.elements;

public enum URLLCServiceCategory {
    DISCRETE_AUTOMATION,
    PROCESS_AUTOMATION_REMOTE_CONTROL,
    PROCESS_AUTOMATION_MONITORING,
    ELECTRICITY_DISTRIBUTION_HIGH_VOLTAGE,
    ELECTRICITY_DISTRIBUTION_MEDIUM_VOLTAGE,
    INTELLIGENT_TRANSPORT_SYSTEMS_INFRASTRUCTURE_BACKHAUL
}
